name: Linux Test

on:
  push:
  pull_request:
    types: [opened]
  schedule:
    - cron: '23 4 * * 2'

jobs:
  test-linux:
    name: test on Linux

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Perl version
        run: perl -V
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cpanminus libmoo-perl libmoox-singleton-perl libtext-asciitable-perl
      - name: Test
        run: |
          make
